- hosts: ubuntu
  remote_user: root
  become: true
  vars:
      version_number: '2.4.1'
      server: 'kishore'
  tasks:
     - name: Template a file to /etc/file.conf
       ansible.builtin.template:
        src: example_template.j2
        dest: /etc/file.conf
